### ISSUE TITLE
DEV - Q - Merge code

### ISSUE THREAD

**Issue by tiadal** [bohgman/DIVIMA#4]
Hello,

can you please check if you can accept the pull request or give us full access to the repo? Somehow I can't merge.

Thanks

**Comment by bohgman** [comment]
I do not know how to change the right. Did it work now?

**Comment by dariakhr** [comment]
yes, thanks a lot!

**Comment by tiadal** [comment]
remote: Permission to bohgman/DIVIMA.git denied to tiadal.
fatal: unable to access 'https://github.com/bohgman/DIVIMA.git/': The requested URL returned error: 403

I am still not able to push on main, can you check the rights please?

**Comment by tiadal** [comment]
I created another pull request, please accept it or check "write rights" for me and Daria.
Thanks

**Comment by bohgman** [comment]
![grafik](https://user-images.githubusercontent.com/44813766/123975636-c9a4d000-d9bd-11eb-9dce-a3d490c35913.png)

It is a pending invitation for you in the access rights. Please check this!

**Comment by tiadal** [comment]
It went in spam and now it's expired, could you please send it again?
I am really sorry for it, my bad.
