### ISSUE TITLE
BIZ - Q - Who is the operator

### ISSUE THREAD

**Issue by tiadal** [bohgman/DIVIMA#5]
Hello,

who is supposed to operate the app? Can a visitor enter her data by herself or is there always a guard/whoever from the company and this app is on his terminal?

Can you describe a simple flow?

Thanks

**Comment by bohgman** [comment]
Hello,

There is no provision for a visitor to make entries themselves. Thus, the guard should check the entry and prevent incorrect entries. However, it would be conceivable that location, key and parking spaces can only be created by a user with admin rights.

Best regards
